[project]
name = "timeseriesanalysis"
version = "0.3.0"
description = "Python bindings for TimeSeriesAnalysis"
readme = "README.md"
authors = [
    { name = "Equinor", email = "equinor" }
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "numpy>=2.4.4",
    "pythonnet>=3.0.5",
]

[project.scripts]
timeseriesanalysis = "timeseriesanalysis:main"
check-missing-classes = "cli.class_discovery:main"
generate-type-stubs = "cli.type_generation:main"
publish-assemblies = "cli.publish_assemblies:main"
publish-assemblies-ci = "cli.publish_assemblies:main_ci"
report-missing-tests = "cli.report_test_manifest:main"

[build-system]
requires = ["uv_build>=0.9.1,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["timeseriesanalysis", "cli"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.16.7",
]
