from timeseriesanalysis._runtime import Runtime
from timeseriesanalysis.dotnet_proxy import DotNetProxy, DotNetStaticProxy
from timeseriesanalysis.dynamic import (
    BadDataFinder,
    ClosedLoopGainGlobalSearchResults,
    ClosedLoopUnitIdentifier,
    Comment,
    CommonDataPreprocessor,
    ConnectionParser,
    DatasetDownsampler,
    DisturbanceCalculator,
    Divide,
    DivideParameters,
    FitScoreCalculator,
    FittingInfo,
    FittingSpecs,
    FrozenDataDetector,
    GainSchedFittingSpecs,
    GainSchedIdentifier,
    GainSchedIdentWarnings,
    GainSchedModel,
    GainSchedParameters,
    GainSchedSubModelResults,
    GainSchedWarnings,
    ISimulatableModel,
    ModelBaseClass,
    ModelParametersBaseClass,
    ModelType,
    OversampledDataDetector,
    PidAntiSurgeParams,
    PidController,
    PidControllerType,
    PidFeedForward,
    PidFiltering,
    PidGainScheduling,
    PidIdentifier,
    PidIdentWarnings,
    PidModel,
    PidModelInputsIdx,
    PidParameters,
    PidScaling,
    PidTuning,
    PlantSimulator,
    PlantSimulatorHelper,
    PlantSimulatorInitializer,
    PlantSimulatorSerializer,
    ProcessTimeDelayIdentWarnings,
    Select,
    SerializeHelper,
    SignalNamer,
    SignalType,
    TimeDelay,
    TimeDelaySamples,
    UnitDataSet,
    UnitIdentifier,
    UnitIdentWarnings,
    UnitModel,
    UnitParameters,
    UnitTimeDelayIdentifier,
)
from timeseriesanalysis.filters import (
    BandPass,
    HighPass,
    LowPass,
    MovingAvg,
    RecursiveAverage,
    SecondOrder,
)
from timeseriesanalysis.core import (
    Array2D,
    CorrelationCalculator,
    Index,
    Matrix,
    Shared,
    SignalPeriodEstimator,
    TimeSeries,
    TimeSeriesDataSet,
    Vec,
)
from timeseriesanalysis.utilities import (
    CSV,
    CsvContent,
    ParserFeedback,
    Plot,
    Plot4Test,
    PlotGain,
    PlotXY,
    SigmaXml,
    SignificantDigits,
    StringToFileWriter,
    TimeSeriesCreator,
    UnixTime,
    XYTable,
)

__all__ = [
    "Array2D",
    "Array2DExtensionMethods",
    "Array2DGeneric",
    "BadDataFinder",
    "BandPass",
    "ClosedLoopGainGlobalSearchResults",
    "ClosedLoopUnitIdentifier",
    "Comment",
    "CommonDataPreprocessor",
    "ConnectionParser",
    "CorrelationCalculator",
    "CSV",
    "CsvContent",
    "DatasetDownsampler",
    "DisturbanceCalculator",
    "Divide",
    "DivideParameters",
    "DotNetProxy",
    "DotNetStaticProxy",
    "FitScoreCalculator",
    "FittingInfo",
    "FittingSpecs",
    "FrozenDataDetector",
    "GainSchedFittingSpecs",
    "GainSchedIdentifier",
    "GainSchedIdentWarnings",
    "GainSchedModel",
    "GainSchedParameters",
    "GainSchedSubModelResults",
    "GainSchedWarnings",
    "HighPass",
    "Index",
    "ISimulatableModel",
    "LowPass",
    "Matrix",
    "ModelBaseClass",
    "ModelParametersBaseClass",
    "ModelType",
    "MovingAvg",
    "OversampledDataDetector",
    "ParserFeedback",
    "PidAntiSurgeParams",
    "PidController",
    "PidControllerType",
    "PidFeedForward",
    "PidFiltering",
    "PidGainScheduling",
    "PidIdentifier",
    "PidIdentWarnings",
    "PidModel",
    "PidModelInputsIdx",
    "PidParameters",
    "PidScaling",
    "PidTuning",
    "PlantSimulator",
    "PlantSimulatorHelper",
    "PlantSimulatorInitializer",
    "PlantSimulatorSerializer",
    "Plot",
    "Plot4Test",
    "PlotGain",
    "PlotXY",
    "ProcessTimeDelayIdentWarnings",
    "RecursiveAverage",
    "Runtime",
    "SecondOrder",
    "Select",
    "SerializeHelper",
    "Shared",
    "SigmaXml",
    "SignalNamer",
    "SignalPeriodEstimator",
    "SignalType",
    "SignificantDigits",
    "StringToFileWriter",
    "TimeSeries",
    "TimeDelay",
    "TimeDelaySamples",
    "TimeSeriesCreator",
    "TimeSeriesDataSet",
    "UnitDataSet",
    "UnitIdentifier",
    "UnitIdentWarnings",
    "UnitModel",
    "UnitParameters",
    "UnitTimeDelayIdentifier",
    "UnixTime",
    "Vec",
    "XYTable",
]

# Auto-initialize .NET runtime on import
Runtime().initialize()


def main() -> None:
    vec = Vec()

    a = [1.0, 2.0, 3.0]
    b = [4.0, 5.0, 6.0]
    result = vec.Add(a, b)

    print(f"vec.add({a}, {b}) = {result}")
